[package]
name = "usage-query"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
domain.workspace = true
reqwest.workspace = true
rquickjs = { version = "0.8", features = ["array-buffer", "classes"] }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]
tempfile.workspace = true
